# Generated by Django 2.1.3 on 2021-03-27 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description')),
                ('is_active', models.CharField(choices=[(1, 'Y'), (2, 'N')], db_column='is_active', default='N', help_text="'Y' or 'N'", max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at', default=django.utils.timezone.now)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'db_table': 'PRODUCT_DATA',
            },
        ),
    ]
